version: '3.8'

services:
  nvd-monitor:
    build: .
    container_name: nvd-monitor
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config/config.ini
    volumes:
      - ./config:/config
      - nvd_logs:/var/log/nvd-monitor
      - nvd_data:/var/lib/nvd-monitor
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nvd-network

  mysql:
    image: mysql:8.0
    container_name: nvd-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-nvd_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nvd_monitor}
      MYSQL_USER: ${MYSQL_USER:-nvd_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-nvd_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - nvd-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nvd-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-nvd_user}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-nvd_password}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - nvd-network

volumes:
  mysql_data:
  nvd_logs:
  nvd_data:

networks:
  nvd-network:
    driver: bridge
